module.exports.dataPerformance = [
  {
    name: "Jan",
    Patient: 40,
    ActivePatient: 24,
    Complete: 17,
    Referrals: 20,
  },
  {
    name: "Feb",
    Patient: 50,
    ActivePatient: 15,
    Complete: 20,
    Referrals: 12,
  },
  {
    name: "Mar",
    Patient: 20,
    ActivePatient: 4,
    Complete: 7,
    Referrals: 10,
  },
  {
    name: "Apr",
    Patient: 60,
    ActivePatient: 18,
    Complete: 12,
    Referrals: 5,
  },
  {
    name: "May",
    Patient: 10,
    ActivePatient: 2,
    Complete: 0,
    Referrals: 5,
  },
  {
    name: "Jun",
    Patient: 120,
    ActivePatient: 24,
    Complete: 17,
    Referrals: 20,
  },
  {
    name: "Jul",
    Patient: 140,
    ActivePatient: 24,
    Complete: 100,
    Referrals: 20,
  },
  {
    name: "Aug",
    Patient: 90,
    ActivePatient: 24,
    Complete: 40,
    Referrals: 20,
  },
  {
    name: "Sept",
    Patient: 200,
    ActivePatient: 24,
    Complete: 55,
    Referrals: 20,
  },
  {
    name: "Sept",
    Patient: 180,
    ActivePatient: 24,
    Complete: 20,
    Referrals: 20,
  },
  {
    name: "Oct",
    Patient: 150,
    ActivePatient: 24,
    Complete: 17,
    Referrals: 20,
  },
  {
    name: "Dec",
    Patient: 225,
    ActivePatient: 24,
    Complete: 27,
    Referrals: 20,
  },
];
