const DiagnosisData = [
  {
    id: 1,
    diagnosis_id: '',
    diagnosis_name: "(J30.9) Allergic rhinitis, unspecified",
    status: "Active",
    from_date: "2022-05-16",
    onset_year: 2023,
    sequence: 'sequence',
    reports: 'reports',
  },
  {
    id: 2,
    diagnosis_id: '',
    diagnosis_name: "(10002) Allergic rhinitis, unspecified",
    status: "Active",
    from_date: "2022-05-16",
    onset_year: 2023,
    sequence: 'sequence',
    reports: 'reports',
  },
  // {
  //   id: 2,
  //   title: "(10002) Allergic rhinitis, unspecified",
  //   acuity: "Chronic",
  //   startDate: "09/15/16",
  //   encounterComment: "Rhinitis worstened by Julian Provider on 04/15/21",
  // },
  // {
  //   id: 3,
  //   title: "(10003) Allergic rhinitis, unspecified",
  //   acuity: "Chronic",
  //   startDate: "09/15/16",
  //   encounterComment: "Rhinitis worstened by Julian Provider on 04/15/21",
  // },
  // {
  //   id: 4,
  //   title: "(10004) Allergic rhinitis, unspecified",
  //   acuity: "Chronic",
  //   startDate: "09/15/16",
  //   encounterComment: "Rhinitis worstened by Julian Provider on 04/15/21",
  // },
  // {
  //   id: 5,
  //   title: "(10005) Allergic rhinitis, unspecified",
  //   acuity: "Chronic",
  //   startDate: "09/15/16",
  //   encounterComment: "Rhinitis worstened by Julian Provider on 04/15/21",
  // },
  // {
  //   id: 6,
  //   title: "(10006) Allergic rhinitis, unspecified",
  //   acuity: "Chronic",
  //   startDate: "09/15/16",
  //   encounterComment: "Rhinitis worstened by Julian Provider on 04/15/21",
  // },
  // {
  //   id: 7,
  //   title: "(10007) Allergic rhinitis, unspecified",
  //   acuity: "Chronic",
  //   startDate: "09/15/16",
  //   encounterComment: "Rhinitis worstened by Julian Provider on 04/15/21",
  // },
];

export default DiagnosisData;
