export const dataApi = [
    {
      id: 1,
      componentName: "Blood Glucose (Random)",
      displayName: "Blood Glucose (Random)",
      unit: "mg/dl",
      range: "70-140",
      description: "test",
      method: "GOD/POD",
      controlType: "",
      valueType: "number",
      valueLookUp: "",
    },
    {
      id: 2,
      componentName: "24 hrs. Urine Creatinine",
      displayName: "24 hrs. Urine Creatinine",
      unit: "mg/24hrs",
      range: "",
      description: "",
      method: "Pyrogallol Red",
      controlType: "TextBox",
      valueType: "number",
      valueLookUp: "",
    },
    {
      id: 3,
      componentName: "A/G ratio",
      displayName: "A/G ratio",
      unit: "",
      range: "1.5",
      description: "test",
      method: "",
      controlType: "",
      valueType: "number",
      valueLookUp: "",
    },
    {
      id: 4,
      componentName: "AFP",
      displayName: "AFP",
      unit: "ng/mlL",
      range: "0.89-8.78",
      description: "0.89-8.78",
      method: "",
      controlType: "number",
      valueType: "",
      valueLookUp: "",
    },
    {
      id: 5,
      componentName: "Albumin",
      displayName: "Albumin",
      unit: "g/dl",
      range: "3.5-5.2",
      description: "3.50-5.20",
      method: "BGG",
      controlType: "TextBox",
      valueType: "number",
      valueLookUp: "",
    },
  ];
  