export const anchorTable = [
  {
    name: "id",
    label: "Id",
    type: "static",
    initialValue: "",
    hidden: false,
  },
  {
    name: "investigation",
    label: "Investigation",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "selecType",
    label: "Selec Type",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "details",
    label: "Details",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "date",
    label: "Date",
    type: "text",
    initialValue: 0,
    width: "150",
    hidden: false,
  },
  {
    name: "specialInstruction",
    label: "Special Instruction",
    type: "text",
    initialValue: 0,
    width: "200",
    hidden: false,
  },
];
export const dataApi = [
  {
    id: 1,
    investigation: "CBC",
    selecType: "auto",
    details: "250mg",
    date: "04/25/2022",
    specialInstruction: "Lorem ipsum Lorem ipsum Lorem ipsum",
  },
  {
    id: 2,
    investigation: "KFT",
    selecType: "auto",
    details: "500mg",
    date: "10/30/2021",
    specialInstruction: "Lorem ipsum Lorem ipsum Lorem ipsum",
  },
  {
    id: 3,
    investigation: "SGOT",
    selecType: "auto",
    details: "1000mg",
    date: "09/05/2021",
    specialInstruction: "Lorem ipsum Lorem ipsum Lorem ipsum",
  },
  {
    id: 4,
    investigation: "CHEST X-RAY",
    selecType: "auto",
    details: "500mg",
    date: "06/22/2020",
    specialInstruction: "Lorem ipsum Lorem ipsum Lorem ipsum",
  },
  {
    id: 5,
    investigation: "URINE R/M",
    selecType: "auto",
    details: "250mg",
    date: "01/02/2021",
    specialInstruction: "Lorem ipsum Lorem ipsum Lorem ipsum",
  },
  {
    id: 6,
    investigation: "KFT",
    selecType: "auto",
    details: "500mg",
    date: "4/25/2022",
    specialInstruction: "Lorem ipsum Lorem ipsum Lorem ipsum",
  },
];
