export const anchorTable = [
  {
    name: "id",
    label: "Id",
    type: "static",
    initialValue: "",
    hidden: true,
  },
  {
    name: "form",
    label: "Form",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "genericName",
    label: "Generic Name",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "strength",
    label: "Strength",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "brandName",
    label: "Brand Name",
    type: "text",
    initialValue: 0,
    width: "150",
    hidden: false,
  },
  {
    name: "route",
    label: "Route",
    type: "text",
    initialValue: 0,
    width: "150",
    hidden: false,
  },
  {
    name: "administration",
    label: "Administration",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "frequency",
    label: "Frequency",
    type: "number",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "duration",
    label: "Duration",
    type: "number",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "afterPlan",
    label: "After Plan",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  ,
  {
    name: "linkDiagnosis",
    label: "Link Diagnosis",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
];
export const dataApi = [
  {
    id: 1,
    sequence: "tablet1",
    ICD10: "A90",
    diagnosis: "Dengue",
    startDate: "20/4/2022",
    status: "Active",
    addedBy: "Dr Ravi",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 2,
    sequence: "tablet1",
    ICD10: "A91",
    diagnosis: "Allergies",
    startDate: "15/05/2022",
    status: "Active",
    addedBy: "Dr Ravi",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 3,
    sequence: "tablet1",
    ICD10: "A92",
    diagnosis: "Colds and Flu",
    startDate: "10/04/2022",
    status: "Active",
    addedBy: "Dr Mukesh",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 4,
    sequence: "tablet1",
    ICD10: "A93",
    diagnosis: "Diarrhea",
    startDate: "22/24/2022",
    status: "Active",
    addedBy: "Dr Radha",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 5,
    sequence: "tablet1",
    ICD10: "A94",
    diagnosis: "Mononucleosis",
    startDate: "01/05/2022",
    status: "Active",
    addedBy: "Dr Rakesh",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 6,
    sequence: "tablet1",
    ICD10: "A95",
    diagnosis: "Dengue",
    startDate: "11/01/2022",
    status: "Active",
    addedBy: "Dr Mohan",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 7,
    sequence: "tablet1",
    ICD10: "A96",
    diagnosis: "Stomach Aches",
    startDate: "22/4/2022",
    status: "Active",
    addedBy: "Dr Dristi",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 8,
    sequence: "tablet1",
    ICD10: "A97",
    diagnosis: "Dengue",
    startDate: "22/4/2022",
    status: "Active",
    addedBy: "Dr Ravi",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 9,
    sequence: "tablet1",
    ICD10: "A98",
    diagnosis: "Conjunctivitis",
    startDate: "22/4/2022",
    status: "Active",
    addedBy: "Dr Ravi",
    linkReport: "linkTo Report",
    edited: false,
  },
  {
    id: 10,
    sequence: "tablet1",
    ICD10: "A99",
    diagnosis: "Dengue",
    startDate: "22/4/2022",
    status: "Active",
    addedBy: "Dr Shristi",
    linkReport: "linkTo Report",
    edited: false,
  },
];
