export const dataApi = [
  {
    id: "pt1",
    name: "Ravi Kumer",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt2",
    name: "Shyam Singh",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt3",
    name: "Ajit Singh",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt4",
    name: "Vikash Kumar",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt5",
    name: "Radha Singh",
    dob: "28/09/1996 ",
    gender: "Female",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt6",
    name: "Suresh Singh",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt7",
    name: "Deepak Kumar",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt8",
    name: "Monu Singh",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt9",
    name: "Arun Kumar",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
  {
    id: "pt10",
    name: "Manish Singh",
    dob: "28/09/1996 ",
    gender: "Male",
    email: "xyz@gmail.com",
    mobileNumber: "+91 9874563210",
    address: "XYZ, Indore",
    diagnosis: "Fever",
  },
];
