export const dataApi = [
  {
    id: "pt1",
    name: "Ravi Kumar",
    age: "24 Year",
    gender: "Male",
    date: "28/09/2022",
    time: "08:40 To 12:40",
    diagnosis: "Fever, Sugar",
    doctorId: "D01",
    doctorName: "Dr. Dristi",
    speciality: "Speciality",
    type: "argent",
    billing: "Approved",
  },
  {
    id: "pt2",
    name: "Shyam Singh",
    age: "26 Year",
    gender: "Male",
    date: "28/05/2022",
    time: "10:00 To 12:00",
    diagnosis: "Fever, Sugar",
    doctorId: "D02",
    doctorName: "Dr. Ram",
    speciality: "Speciality",
    type: "Routing",
    billing: "Pending",
  },
  {
    id: "pt3",
    name: "Rahul Kumar",
    age: "30 Year",
    gender: "Male",
    date: "12/10/2022",
    time: "09:40 To 12:40",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    type: "argent",
    billing: "Approved",
  },
  {
    id: "pt4",
    name: "Ajit Singh",
    age: "22 Year",
    gender: "Male",
    date: "28/05/2022",
    time: "10:00 To 12:00",
    diagnosis: "Fever, Sugar",
    doctorId: "D02",
    doctorName: "Dr. Ram",
    speciality: "Speciality",
    type: "Routing",
    billing: "Pending",
  },
  {
    id: "pt5",
    name: "Suresh Kumar",
    age: "23 Year",
    gender: "Male",
    date: "12/10/2022",
    time: "09:40 To 12:40",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    type: "argent",
    billing: "Approved",
  },
  {
    id: "pt6",
    name: "Radha Kumari",
    age: "20 Year",
    gender: "Female",
    date: "12/10/2022",
    time: "09:40 To 12:40",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    type: "Routing",
    billing: "Pending",
  },
  {
    id: "pt7",
    name: "Shyam Singh",
    age: "26 Year",
    gender: "Male",
    date: "28/05/2022",
    time: "10:00 To 12:00",
    diagnosis: "Fever, Sugar",
    doctorId: "D02",
    doctorName: "Dr. Ram",
    speciality: "Speciality",
    type: "Routing",
    billing: "Pending",
  },
  {
    id: "pt8",
    name: "Rahul Kumar",
    age: "30 Year",
    gender: "Male",
    date: "12/10/2022",
    time: "09:40 To 12:40",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    type: "argent",
    billing: "Approved",
  },
  {
    id: "pt9",
    name: "Ajit Singh",
    age: "22 Year",
    gender: "Male",
    date: "28/05/2022",
    time: "10:00 To 12:00",
    diagnosis: "Fever, Sugar",
    doctorId: "D02",
    doctorName: "Dr. Ram",
    speciality: "Speciality",
    type: "Routing",
    billing: "Pending",
  },
  {
    id: "pt10",
    name: "Suresh Kumar",
    age: "23 Year",
    gender: "Male",
    date: "12/10/2022",
    time: "09:40 To 12:40",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    type: "argent",
    billing: "Approved",
  },
];
