export const dataApi = [
  {
    id: "1",
    clinicName: "General Care Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "joined",
  },
  {
    id: "2",
    clinicName: "Complete Health Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "Left",
  },
  {
    id: "3",
    clinicName: "Recovery Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "Open",
  },
  {
    id: "4",
    clinicName: "Dermatology Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "Closed",
  },
  {
    id: "5",
    clinicName: "Eye Care Center",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "Pending",
  },
  {
    id: "6",
    clinicName: "Health & Care Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "Declined",
  },
  {
    id: "7",
    clinicName: "Arthritis Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "Acceped",
  },
  {
    id: "8",
    clinicName: "General Care Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "joined",
  },
  {
    id: "9",
    clinicName: "Complete Health Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "joined",
  },
  {
    id: "10",
    clinicName: "Arthritis Clinic",
    admin: "admin",
    phoneNumber: "+91 9856321175",
    address: "xyz Square , near of Shiva Temple",
    status: "joined",
  },
];
