export const dataApi = [
  {
    id: "pt1",
    name: "Ravi Kumar",
    age: "24 Year",
    gender: "Male",
    admissionDate: "28/09/2022",
    dischargeDate: "15/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D02",
    doctorName: "Dr. Ram",
    speciality: "Speciality",
    ward: "1",
    bedNo: "100",
    billing: "Approved",
  },
  {
    id: "pt2",
    name: "Shyam Singh",
    age: "26 Year",
    gender: "Male",
    admissionDate: "28/06/2022",
    dischargeDate: "10/10/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D01",
    doctorName: "Dr. Dristi",
    speciality: "Speciality",
    ward: "5",
    bedNo: "25",
    billing: "Approved",
  },
  {
    id: "pt3",
    name: "Rahul Kumar",
    age: "30 Year",
    gender: "Male",
    admissionDate: "08/05/2022",
    dischargeDate: "01/12/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    ward: "5",
    bedNo: "60",
    billing: "Pending",
  },
  {
    id: "pt4",
    name: "Ajit Singh",
    age: "22 Year",
    gender: "Male",
    admissionDate: "10/02/2022",
    dischargeDate: "05/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D01",
    doctorName: "Dr. Dristi",
    speciality: "Speciality",
    ward: "11",
    bedNo: "70",
    billing: "Approved",
  },
  {
    id: "pt5",
    name: "Suresh Kumar",
    age: "23 Year",
    gender: "Male",
    admissionDate: "28/09/2022",
    dischargeDate: "16/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    ward: "1",
    bedNo: "80",
    billing: "Pending",
  },
  {
    id: "pt6",
    name: "Radha Kumari",
    age: "20 Year",
    gender: "Female",
    admissionDate: "28/09/2022",
    dischargeDate: "20/10/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    ward: "1",
    bedNo: "90",
    billing: "Pending",
  },
  {
    id: "pt7",
    name: "Shyam Singh",
    age: "26 Year",
    gender: "Male",
    admissionDate: "28/09/2022",
    dischargeDate: "15/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D01",
    doctorName: "Dr. Dristi",
    speciality: "Speciality",
    ward: "15",
    bedNo: "100",
    billing: "Approved",
  },
  {
    id: "pt8",
    name: "Rahul Kumar",
    age: "30 Year",
    gender: "Male",
    admissionDate: "28/09/2022",
    dischargeDate: "15/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    ward: "15",
    bedNo: "102",
    billing: "Approved",
  },
  {
    id: "pt9",
    name: "Ajit Singh",
    age: "22 Year",
    gender: "Male",
    admissionDate: "28/09/2022",
    dischargeDate: "15/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    ward: "15",
    bedNo: "102",
    billing: "Approved",
  },
  {
    id: "pt10",
    name: "Suresh Kumar",
    age: "23 Year",
    gender: "Male",
    admissionDate: "28/09/2022",
    dischargeDate: "15/11/2022",
    diagnosis: "Fever, Sugar",
    doctorId: "D03",
    doctorName: "Dr. Radha",
    speciality: "Speciality",
    ward: "15",
    bedNo: "102",
    billing: "Approved",
  },
];
