const MedicationData = [
  {
    id: 1,
    form: "tablet",
    genericName: "acetaminophen",
    strength: "500mg",
    brandName: "Cronic",
    route: "Oral",
    administration: "New",
    frequency: "0-0-1",
    duration: "5 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 2,
    form: "tablet",
    genericName: "acetaminophen",
    strength: "500mg",
    brandName: "Lanol",
    route: "Oral",
    administration: "New",
    frequency: "0-0-1",
    duration: "5 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 3,
    form: "tablet",
    genericName: "acetaminophen",
    strength: "500mg",
    brandName: "Dolo",
    route: "Oral",
    administration: "New",
    frequency: "0-0-1",
    duration: "5 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
];

export default MedicationData;
