export const anchorTable = [
  {
    name: "id",
    label: "Id",
    type: "static",
    initialValue: "",
    hidden: true,
  },
  {
    name: "form",
    label: "Form",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "genericName",
    label: "Generic Name",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "strength",
    label: "Strength",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "brandName",
    label: "Brand Name",
    type: "text",
    initialValue: 0,
    width: "150",
    hidden: false,
  },
  {
    name: "route",
    label: "Route",
    type: "text",
    initialValue: 0,
    width: "150",
    hidden: false,
  },
  {
    name: "administration",
    label: "Administration",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "frequency",
    label: "Frequency",
    type: "number",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "duration",
    label: "Duration",
    type: "number",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  {
    name: "afterPlan",
    label: "After Plan",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
  ,
  {
    name: "linkDiagnosis",
    label: "Link Diagnosis",
    type: "text",
    initialValue: 0,
    width: "100",
    hidden: false,
  },
];
export const dataApi = [
  {
    id: 1,
    form: "Tablet",
    genericName: "Acetaminophen",
    strength: "1000mg",
    brandName: "Cronic",
    route: "Oral",
    administration: "New",
    frequency: "0-0-1",
    duration: "7 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 2,
    form: "Capsule",
    genericName: "Paracitamol",
    strength: "500mg",
    brandName: "Dolo",
    route: "Nasal",
    administration: "New",
    frequency: "0-0-1",
    duration: "10 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 3,
    form: "Syrup",
    genericName: "Paracitamol",
    strength: "250mg",
    brandName: "Cronic",
    route: "Rectal",
    administration: "New",
    frequency: "0-0-1",
    duration: "5 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 4,
    form: "Powder",
    genericName: "Aetaminophen",
    strength: "500mg",
    brandName: "Oral",
    route: "Gargle",
    administration: "New",
    frequency: "0-0-1",
    duration: "15 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 5,
    form: "Injection",
    genericName: "Paracitamol",
    strength: "1000mg",
    brandName: "Cronic",
    route: "Through RT",
    administration: "New",
    frequency: "0-0-1",
    duration: "30 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
  {
    id: 6,
    form: "Respule",
    genericName: "acetaminophen",
    strength: "500mg",
    brandName: "Lanol",
    route: "IntraVenous",
    administration: "New",
    frequency: "0-0-1",
    duration: "14 days",
    afterPlan: "somethings",
    linkDiagnosis: "link here",
  },
];
