// Redux Form
export const INIT = "INIT";
export const CLEAR = "CLEAR";

// USER LOGIN ACTION
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

// USER REGISTER ACTION
export const USER_REGISTER = "USER_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// PATIENT ACTION
export const SET_PATIENT = "SET_PATIENT";
export const RESET_PATIENT = "RESET_PATIENT";

// ENCOUNTER ACTION
export const ADD_ENCOUNTER = "ADD_ENCOUNTER";
export const REMOVE_ENCOUNTER = "REMOVE_ENCOUNTER";
export const CLEAR_ENCOUNTER = "CLEAR_ENCOUNTER";

// constants/reduxFormConstants.js

export const GENERATE_OTP_REQUEST = "GENERATE_OTP_REQUEST";
export const GENERATE_OTP_SUCCESS = "GENERATE_OTP_SUCCESS";
export const GENERATE_OTP_FAILURE = "GENERATE_OTP_FAILURE";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const CREATE_HEALTH_ID_REQUEST = "CREATE_HEALTH_ID_REQUEST";
export const CREATE_HEALTH_ID_SUCCESS = "CREATE_HEALTH_ID_SUCCESS";
export const CREATE_HEALTH_ID_FAILURE = "CREATE_HEALTH_ID_FAILURE";

// constants/reduxFormConstants.js

export const GENERATE_OTP_AADHAR_REQUEST = "GENERATE_OTP_REQUEST";
export const GENERATE_OTP_AADHAR_SUCCESS = "GENERATE_OTP_SUCCESS";
export const GENERATE_OTP_AADHAR_FAILURE = "GENERATE_OTP_FAILURE";

export const RESEND_OTP_AADHAR_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_AADHAR_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_AADHAR_FAILURE = "RESEND_OTP_FAILURE";

export const VERIFY_OTP_AADHAR_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_AADHAR_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_AADHAR_FAILURE = "VERIFY_OTP_FAILURE";

export const CREATE_HEALTH_ID_AADHAR_REQUEST = "CREATE_HEALTH_ID_REQUEST";
export const CREATE_HEALTH_ID_AADHAR_SUCCESS = "CREATE_HEALTH_ID_SUCCESS";
export const CREATE_HEALTH_ID_AADHAR_FAILURE = "CREATE_HEALTH_ID_FAILURE";
